#! /bin/sh

sxhkd &
xsetroot -cursor_name left_ptr &

bspc monitor HDMI-1 -d term files code misc chat
bspc monitor DVI-D-1 -d  www vm yt mail music


bspc config border_width        1
bspc config window_gap          40

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config single_monocle true
bspc config gapless_monocle      false


bspc rule -a alacritty desktop='^1' follow=on
bspc rule -a Pcmanfm desktop='^2' follow=on
bspc rule -a code-oss desktop='^3' state=floating follow=on
bspc rule -a discord desktop='^5'
bspc rule -a tweetdeck-nativefier-4d2c61 desktop='^5'
bspc rule -a whatsapp-nativefier-d40211 desktop='^5'
bspc rule -a Firefox desktop='^6' follow=on
bspc rule -a mpv state=floating desktop='^8' follow=on
bspc rule -a qBittorrent desktop='^2' follow=on
bspc rule -a feh state=floating follow=on
bspc rule -a Screenkey manage=off
bspc rule -a protonmail-nativefier-9603f8 desktop='^9'
bspc rule -a Spotify desktop='^10'
bspc rule -a scrcpy desktop='^5' state=floating

picom &
udiskie &
# Spotify &
# whatsapp &
# alacritty -e ncmpcpp &
mpd &
nitrogen --restore &
dunst -config ~/.config/dunst/dunstrc &
sudo sh /home/ross/.config/polybar/scripts/startVPN.sh &
sh ~/.config/polybar/launch.sh &
