#! /bin/bash
arg1=${1:-60}
arg2=${2:-s}
if [ "$arg2" == "m" ]; then
   arg1=$((arg1*60))
elif [ "$arg2" == "h" ]; then
   arg1=$((arg1*60*60))
fi
   date1=$((`date +%s` + $arg1)); 
   while [ "$date1" -ge `date +%s` ]; do 
     echo -ne "$(date -u --date @$(($date1 - `date +%s`)) +%H:%M:%S)\r";
     sleep 0.1
   done
